var chocolateBars = ["snickers", "hundred grand'",  "kitkat", "skittles"];
var addElementToBeginningOfArray = chocolateBars.unshift("milky way");
var destructivelyAddElementToBeginningOfArray = ("3 musketeers",...chocolateBars);
var addElementToBeginningOfArray = ("almond joy",...chocolateBars);
var destructivelyAddElementToBeginningOfArray= (chocolateBars,..."milky way");  
var accessElementInArray = ["cnn", "bbc", "nbc"];
console.log([2]);
var destructivelyRemoveElementFromBeginningOfArray = ["cnn", "bbc", "nbc", "fox news"];
destructivelyRemoveElementFromBeginningOfArray.slice(3);
var remove = removeElementToBeginningOfArray.slice(-2);
var popLast = destructivelyRemoveElementFromBeginningOfArray.pop();